name: Health Check

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checks deployed page /health is accessible
        uses: Jtalk/url-health-check-action@v4
        with:
          url: "https://fullstackopen-pokedex-juhamikael.fly.dev/health"
          max-attempts: 3
          retry-delay: "5s"
          retry-all: false
